"""
Convert PDF legal documents to Markdown text for Leyes-RD-Bot.

This script extracts text from a PDF and creates a Markdown file.
The generated Markdown must still be reviewed manually before being used
as a verified legal source.
"""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCES_DIR = ROOT / "sources_pdf"


def convert_pdf_to_markdown(pdf_path: Path, output_path: Path) -> None:
    """
    Convert a PDF file to a Markdown file.

    Requires:
        pip install pymupdf
    """
    try:
        import fitz  # PyMuPDF
    except ImportError as exc:
        raise SystemExit(
            "Missing dependency: pymupdf. Install it with: pip install pymupdf"
        ) from exc

    if not pdf_path.exists():
        raise FileNotFoundError(f"PDF file not found: {pdf_path}")

    document = fitz.open(pdf_path)
    markdown_parts = []

    markdown_parts.append(
        "<!-- Generated by scripts/pdf_to_markdown.py. Review manually before legal use. -->\n"
    )

    for page_number, page in enumerate(document, start=1):
        page_text = page.get_text("text")
        markdown_parts.append(f"\n\n<!-- page: {page_number} -->\n\n")
        markdown_parts.append(page_text)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(markdown_parts), encoding="utf-8")

    print(f"Converted: {pdf_path}")
    print(f"Output: {output_path}")


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage:")
        print("  python scripts/pdf_to_markdown.py <input_pdf> <output_markdown>")
        print("")
        print("Example:")
        print("  python scripts/pdf_to_markdown.py sources_pdf/ley_358_05.pdf consumidor/ley_358_05_proteccion_consumidor.md")
        return 1

    input_pdf = ROOT / sys.argv[1]
    output_markdown = ROOT / sys.argv[2]

    convert_pdf_to_markdown(input_pdf, output_markdown)
    return 0


if __name__ == "__main__":
    sys.exit(main())
